version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_attendances
    restart: always
    environment:
      POSTGRES_DB: control-attendances
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

